server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
  port: 8080

spring:
  datasource:
    username: jodos
    password: jodos2006
    url: jdbc:postgresql://localhost:5432/spring_security_temp
    driver-class-name: org.postgresql.Driver
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
#    open-in-view: true
  security:

    user:
      password: jodos2006
      name: jodos
  mvc:
    throw-exception-if-no-handler-found: true
jwt:
  secret:jodosjodos
  expiration:86400000
